# server/Dockerfile_device

FROM python:3.10-slim
WORKDIR /app

# Установка зависимостей
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Копирование исходного кода
COPY device_recognition.py .

# Запуск приложения
CMD ["python", "device_recognition.py"]
